server:
  port: 8084

spring:
  application:
    name: notification-service
  autoconfigure:
    exclude:
      - com.alibaba.cloud.nacos.endpoint.NacosDiscoveryEndpointAutoConfiguration
      - org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/cafequeue_notification_db?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: ${MYSQL_USER:cafequeue}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
